### ISSUE TITLE
Embedded icons do not match https://github.com/freetaxii/stix2-graphics

### ISSUE THREAD

**Issue by eliataylor** [traut/stixview#12]
The icons do not match the [stix2-graphics](https://github.com/freetaxii/stix2-graphics). 

For example, 

![Screen Shot 2021-04-16 at 3 10 21 AM](https://user-images.githubusercontent.com/6335974/115009621-53360e80-9e61-11eb-86dc-c68b041614ce.png)

vs.

![freetaxii-stix2-graphics-Graphics-icons-and-diagrams-to-support-STIX-2](https://user-images.githubusercontent.com/6335974/115009384-19fd9e80-9e61-11eb-8607-bb704225b28d.png)

**Comment by traut** [comment]
@eliataylor indeed, they do not. It's because stixview uses own [set of icons](https://github.com/traut/stixview/tree/master/icons), contributed by [EclecticIQ](https://github.com/EclecticIQ) for this project.

**Comment by eliataylor** [comment]
fair enough.

**Comment by eliataylor** [comment]
@traut , thanks for your work here. Before learning how poorly the stix EPS files convert to SVG, I forked your repo to load them for more consistency around our app. 

If curious there's some other minor optimizations: https://github.com/taylormadetraffic/stixview/blob/master/src/viewer.js#L155

If you happen to know of any open source SVG sets using only vector paths, please do tell.

**Comment by traut** [comment]
@eliataylor the icons in this library are under the library's license (BSD 3-Clause), so they are open source. Feel free to use in the scope of the license. 

I'm not aware of any other open-source SVG STIX2 icon sets. Maybe @jordan2175 has SVG originals he can share.

**Comment by jordan2175** [comment]
I can produce SVGs, but no one has asked for them before.

**Comment by eliataylor** [comment]
@jordan2175 , i suppose I could embed the PNGs and use the `filter` prop in css for color changes, but for whatever reason was going towards svgs. If you can easily export clean vectors, please do share :)

@traut , I like the EclecticIQ but it's missing a number of objects we do use.

**Comment by traut** [comment]
@eliataylor could you please list the object types you are missing?

**Comment by eliataylor** [comment]
Although in practice I doubt we will see every one of them, for  the sake of portability I have a test case that checks each type provided by Stix 2:

```
const typeMap = {
    'stix2-adversary-icons-png':['adversary-identity', 'campaign', 'intrusion-set', 'threat-actor'],
    'stix2-ir-icons-png':['coa', 'incident', 'indicator', 'observed-data'],
    'stix2-marking-icons-png':['tlp-amber'],
    'stix2-meta-icons-png':['bundle', 'grouping', 'identity', 'langauge', 'location', 'note', 'opinion', 'report'],
    'stix2-relationship-icons-png':['relationship', 'sighting'],
    'stix2-sco-network-address-icons-png':['domain-name', 'ipv4', 'ipv6', 'mac-addr'],
    'stix2-sco-network-traffic-icons-png':['autonomous-system', 'http', 'network-traffic'],
    'stix2-sco1-icons-png':['email-addr', 'email-msg', 'user-account'],
    'stix2-targeting-icons-png':['source', 'victim-target', 'victim', 'vulnerability'],
    'stix2-ttp-icons-png':['malware', 'malware-analysis', 'tool', 'attack-pattern', 'infrastructure']
}
```

(in case it might help others, i `convert` my icons directly from the public [repo](https://github.com/freetaxii/stix2-graphics/tree/master/icons) with:

~~~

let iconMap = {};

for (let dir in typeMap) {
    const allFolders = fs.readdirSync(baseDir + 'png/' + dir);
    allFolders.forEach(o => {
        if (o.indexOf('noback-flat') > -1 || o.indexOf('round-flat') > -1) {
            let newName = o.replace('-300-dpi', '-40x40');
            let prefix = o.indexOf('noback-flat') > -1 ? o.substr(0, o.indexOf('-noback-')) : o.substr(0, o.indexOf('-round-'));
            if (newName.indexOf('coa-') === 0) {
                newName = newName.replace('coa-', 'course-of-action-');
                prefix = 'course-of-action';
            }
            iconMap[prefix] = '/assets/stix/' + newName;

            execSync(`convert -thumbnail 250x40 -unsharp 0x1 -quality 100  ${baseDir + dir+'/'+o} ${destination + newName}`);

            newName = newName.replace('.png', '.svg').replace('-40x40', '');
            let cmd = `/usr/local/bin/uniconvertor ${baseDir}/png/${dir}/${o} ${destination + newName}`;
            // let cmd = `/Applications/Inkscape.app/Contents/MacOS/inkscape --export-type=svg --export-area-page=${svgDir + '/' + o} --export-filename=${destination + newName} `;
            execSync(cmd);
        }
    })
}
~~~

**Comment by traut** [comment]
@eliataylor understood, thank you. Stixview will try to render new object types distinctly (by using [the first letter of the object type](https://github.com/traut/stixview/blob/master/src/viewer.js#L417)) but it might be too subtle. 

Thanks for the code!

**Comment by traut** [comment]
@eliataylor btw, could you share the use case? Are you using stixview in the environment where freetaxii's icons are commonly used?

**Comment by eliataylor** [comment]
@traut , sorry for dropping off. I got swept away with other work.

I'm sure our use cases are similar in that we want to visualize reports with all types of stix objects, but also allow users to add / remove any type of object to customize the reports; and indeed contribute to taxii. I haven't yet explored freetaxi icons, but imagine they'd be useful when it comes to that step.

hope that answers the question and again appreciate your work here.

**Comment by traut** [comment]
@eliataylor understood, thank you. As I mentioned stixview will try its best to show unique object-type specific generated icons for non-supported / custom object types, but those will still be stixview-style icons.
