### ISSUE TITLE
Not displaying in Angular app

### ISSUE THREAD

**Issue by iamcootis** [traut/stixview#17]
Any examples of how to get this displaying in an Angular app?
I'm referencing the bundle correctly and just pulled your example directly:
```
<div data-stix-gist-id="6a0fbb0f6e7faf063c748b23f9c7dc62"
         data-show-sidebar=true
         data-disable-mouse-zoom=true
         data-graph-width=500
         data-graph-height=300>
    </div>
```

A div is present but nothing displays.

**Comment by traut** [comment]
@iamcootis could you provide a sample angular app that demonstrates the problem? I'm not familiar with Angular but would love to fix the issue

**Comment by traut** [comment]
`stixview` relies on jQuery's select to find the divs and [populate them on init](https://github.com/traut/stixview/blob/master/src/index.js#L152). Maybe it is not triggered in your Angular app.

**Comment by traut** [comment]
should be fixed in the latest master
