### ISSUE TITLE
Is there a way to directly draw the STIX2 graph from STIX2 JSON?

### ISSUE THREAD

**Issue by KnightChaser** [traut/stixview#32]
Is there a way to directly draw the `stixview` graph from the STIX2 JSON data stored in the JavaScript variable? At least I couldn't find the way to do so unless I "uploaded" the given STIX data to the remote website. Thanks in advance.

**Comment by traut** [comment]
@KnightChaser yes, you can draw the graph from inline data! Here is [the code](https://github.com/traut/stixview/blob/fe8c0c8f47fd89faf5f07c31f1ab80a9f36c5311/src/demos/load-data.html#L58-L59) for [the demo page](https://traut.github.io/stixview/dist/demos/load-data.html) that does it.

**Comment by KnightChaser** [comment]
Thanks for letting me know. This also can be smoothly integrated into the Sveltekit application. Here's the screenshot after successfully rendering STIX2 data visually.

![image](https://github.com/user-attachments/assets/40d66d96-c25f-4b78-89e7-bdf051635009)


(Suppose the variable `fileContent` is a stringified STIX2-compliant bundle object JSON, after importing `stixview` package from unpkg.com.)
```js
// JavaScript part
function initializeStixView() {
	console.log("Initializing STIXView");
	const stixViewGraphElement = document.getElementById("stixview-graph-element");
	const graph = window.stixview.init(
		stixViewGraphElement,
		null,
		() => {
			console.log("Graph loaded");
		}, {}, // no additional data properties
		{
			hideFooter: false,
			showSidebar: true,
			graphWidth: stixViewGraphElement.dataset.graphWidth,
			graphHeight: stixViewGraphElement.dataset.graphHeight,
			onClickNode: function(node) {
				console.log("Clicked node", node);
			}
		}
	)
	graph.loadData(JSON.parse(fileContent));
}

// HTML part
        <!-- stixview graph container -->
        <div id="stixview-graph-element"
             data-graph-width="100%" 
             data-graph-height="40vh">
        </div>
```

**Comment by traut** [comment]
that's very cool, thank you for sharing!
