### ISSUE TITLE
load bundle from file does not work

### ISSUE THREAD

**Issue by VVX7** [traut/stixview#4]
Hi

I've saved the example stix bundles and tried uploading it using the file explorer.
`https://raw.githubusercontent.com/oasis-open/cti-stix2-json-schemas/master/examples/threat-reports/poisonivy.json`

Stixview does not load the file.  I'm only able to load resources by providing a path in the URL.

Thanks :)

**Comment by traut** [comment]
@VVX7 are you trying to load it from the local filesystem with `file://` schema?  It might be that the request is blocked by CORS policy. Please check JS console in your browser to verify.

**Comment by VVX7** [comment]
Loading from local filesystem gives me this error:
```
ReferenceError: readFile is not defined2 stixview.bundle.js:34:980031
    loadDataFromFile https://traut.github.io/stixview/dist/stixview.bundle.js:34
    <anonymous> https://traut.github.io/stixview/dist/demos/viewer.html?bundle=https://raw.githubusercontent.com/oasis-open/cti-stix2-json-schemas/master/examples/threat-reports/poisonivy.json:83
    jQuery 2
        dispatch
        handle
```

I am able to drag and drop a file. That's working as expected.

**Comment by traut** [comment]
@VVX7 indeed, there was an issue - `readFile` func import was missing. I've fixed it in f0af4b1e09afbc6be279ecac63c86c68249ee136, please verify.

**Comment by VVX7** [comment]
Hi @traut 

I'm loading `src/demo/viewer.html` and getting `window.stixview` error.

**Comment by traut** [comment]
@VVX7 `src/demo/*.html` files are the sources for demo pages that need to be build. Run `yarn build` and open `dist/demo/viewer.html`

**Comment by traut** [comment]
@VVX7 indeed, there was an issue with `loadFile` function which should be fixed now. Thank you for the ping!
